palette = 'catppuccin_mocha'

format = """
[](green)\
$username\
[](fg:green bg:peach )\
$directory\
[](fg:peach bg:lavender)\
$git_branch\
[](fg:lavender bg:sapphire)\
$golang\
$java\
$nodejs\
$rust\
[](fg:sapphire bg:mauve)\
$docker_context\
[](fg:mauve bg:blue)\
[ ](fg:blue)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:green fg:base"
style_root = "bg:green fg:base" 
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:peach fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[docker_context]
symbol = " "
style = "bg:mauve fg:base"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:lavender fg:base"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:lavender fg:base"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

